CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Electronics (20 товаров)
INSERT INTO products (name, price, category, image_url) VALUES
('Смартфон Xiaomi Redmi Note 11', 199.99, 'electronics', 'https://via.placeholder.com/150?text=Phone'),
('Ноутбук Lenovo IdeaPad 3', 499.99, 'electronics', 'https://via.placeholder.com/150?text=Laptop'),
('Наушники Sony WH-1000XM4', 349.99, 'electronics', 'https://via.placeholder.com/150?text=Headphones'),
('Планшет Samsung Tab A8', 229.99, 'electronics', 'https://via.placeholder.com/150?text=Tablet'),
('Монитор Dell 24"', 179.99, 'electronics', 'https://via.placeholder.com/150?text=Monitor'),
('Клавиатура Logitech MX Keys', 119.99, 'electronics', 'https://via.placeholder.com/150?text=Keyboard'),
('Мышь Logitech MX Master 3', 99.99, 'electronics', 'https://via.placeholder.com/150?text=Mouse'),
('Внешний диск WD 1TB', 59.99, 'electronics', 'https://via.placeholder.com/150?text=HDD'),
('Роутер TP-Link Archer C6', 49.99, 'electronics', 'https://via.placeholder.com/150?text=Router'),
('Принтер HP LaserJet', 129.99, 'electronics', 'https://via.placeholder.com/150?text=Printer'),
('Фитнес-браслет Xiaomi Mi Band 6', 39.99, 'electronics', 'https://via.placeholder.com/150?text=Band'),
('Умные часы Samsung Galaxy Watch 4', 249.99, 'electronics', 'https://via.placeholder.com/150?text=Watch'),
('Игровая приставка Sony PS5', 499.99, 'electronics', 'https://via.placeholder.com/150?text=PS5'),
('Фотоаппарат Canon EOS 2000D', 399.99, 'electronics', 'https://via.placeholder.com/150?text=Camera'),
('Микрофон Blue Yeti', 129.99, 'electronics', 'https://via.placeholder.com/150?text=Microphone'),
('Веб-камера Logitech C920', 79.99, 'electronics', 'https://via.placeholder.com/150?text=Webcam'),
('Электронная книга Amazon Kindle', 89.99, 'electronics', 'https://via.placeholder.com/150?text=Kindle'),
('Портативная колонка JBL Flip 5', 69.99, 'electronics', 'https://via.placeholder.com/150?text=Speaker'),
('Зарядное устройство Anker 65W', 29.99, 'electronics', 'https://via.placeholder.com/150?text=Charger'),
('SSD Samsung 870 EVO 500GB', 54.99, 'electronics', 'https://via.placeholder.com/150?text=SSD'),

-- Clothing (20 товаров)
('Футболка мужская хлопок', 14.99, 'clothing', 'https://via.placeholder.com/150?text=T-shirt'),
('Джинсы Levi''s 501', 69.99, 'clothing', 'https://via.placeholder.com/150?text=Jeans'),
('Куртка зимняя', 129.99, 'clothing', 'https://via.placeholder.com/150?text=Jacket'),
('Платье вечернее', 89.99, 'clothing', 'https://via.placeholder.com/150?text=Dress'),
('Кроссовки Nike Air', 79.99, 'clothing', 'https://via.placeholder.com/150?text=Sneakers'),
('Рубашка офисная', 34.99, 'clothing', 'https://via.placeholder.com/150?text=Shirt'),
('Шорты летние', 19.99, 'clothing', 'https://via.placeholder.com/150?text=Shorts'),
('Свитер шерстяной', 49.99, 'clothing', 'https://via.placeholder.com/150?text=Sweater'),
('Пальто', 159.99, 'clothing', 'https://via.placeholder.com/150?text=Coat'),
('Брюки классические', 44.99, 'clothing', 'https://via.placeholder.com/150?text=Trousers'),
('Юбка', 29.99, 'clothing', 'https://via.placeholder.com/150?text=Skirt'),
('Худи', 39.99, 'clothing', 'https://via.placeholder.com/150?text=Hoodie'),
('Носки', 4.99, 'clothing', 'https://via.placeholder.com/150?text=Socks'),
('Шапка', 9.99, 'clothing', 'https://via.placeholder.com/150?text=Hat'),
('Перчатки', 7.99, 'clothing', 'https://via.placeholder.com/150?text=Gloves'),
('Шарф', 12.99, 'clothing', 'https://via.placeholder.com/150?text=Scarf'),
('Толстовка', 29.99, 'clothing', 'https://via.placeholder.com/150?text=Sweatshirt'),
('Пиджак', 79.99, 'clothing', 'https://via.placeholder.com/150?text=Blazer'),
('Комбинезон', 59.99, 'clothing', 'https://via.placeholder.com/150?text=Jumpsuit'),
('Купальник', 24.99, 'clothing', 'https://via.placeholder.com/150?text=Swimsuit'),

-- Books (20 товаров)
('Война и мир. Том 1', 12.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('1984', 9.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Мастер и Маргарита', 11.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Преступление и наказание', 10.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Маленький принц', 7.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Гарри Поттер и философский камень', 15.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Унесенные ветром', 14.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Три товарища', 9.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Портрет Дориана Грея', 8.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Гордость и предубеждение', 9.49, 'books', 'https://via.placeholder.com/150?text=Book'),
('Анна Каренина', 11.49, 'books', 'https://via.placeholder.com/150?text=Book'),
('Идиот', 10.49, 'books', 'https://via.placeholder.com/150?text=Book'),
('Братья Карамазовы', 13.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Сто лет одиночества', 12.49, 'books', 'https://via.placeholder.com/150?text=Book'),
('Над пропастью во ржи', 8.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Великий Гэтсби', 9.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Шантарам', 14.49, 'books', 'https://via.placeholder.com/150?text=Book'),
('Алхимик', 7.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Тень ветра', 10.99, 'books', 'https://via.placeholder.com/150?text=Book'),
('Код да Винчи', 11.99, 'books', 'https://via.placeholder.com/150?text=Book');
